### ISSUE TITLE
Bug when removing particles from sim

### ISSUE THREAD

**Issue by emilydeibert** [chelseah/Scatter#7]
Sometimes when running `submit_rebound.py` I get the following error:

`Index passed to particles_remove_id (id = 3) not found in particles array.  Did not remove particle.
Traceback (most recent call last):
  File "submit_rebound.py", line 256, in <module>
    main()
  File "submit_rebound.py", line 176, in main
    sim.remove(id=mid)
  File "/mnt/raid-cita/edeibert/rebound/rebound/simulation.py", line 740, in remove
    raise ValueError("id %d passed to remove_particle was not found.  Did not remove particle.\n"%(id))
ValueError: id 3 passed to remove_particle was not found.  Did not remove particle.`

This always happens for `id=3` in the attempts that I've made to run the code.

**Comment by chelseah** [comment]
@emilydeibert  Which version of code has this bug? The one use pool or the one use Process? 
Can I have the last step output?

**Comment by emilydeibert** [comment]
@chelseah Both versions have this bug. I have tried running it a few times and the number of successful runs changes each time.

There isn't anything in the output file for any of my trials, and the error files only have the above error.

**Comment by chelseah** [comment]
Fixed by add in move_to_com call after add in all the planets
